export const AUTH_START = 'AUTH_START';
export const POST_USER_DATA = 'POST_USER_DATA';
export const AUTH_FAIL = 'AUTH_FAIL';
export const GET_USER_DATA = 'GET_USER_DATA';

// audio data types
export const CREATE_BASE_AUDIO_CONTEXT_AND_ANALYSER = 'CREATE_BASE_AUDIO_CONTEXT_AND_ANALYSER';
export const START_CREATION_AUDIO_DATA = 'START_CREATION_AUDIO_DATA';
export const CREATE_AUDIO_DATA = 'CREATE_AUDIO_DATA';
export const PLAY_PAUSE_SOUND_FROM_FILE = 'PLAY_PAUSE_SOUND_FROM_FILE';
export const CREATE_STREAME_DATA = 'CREATE_STREAME_DATA';
export const START_MUTE_STREAME_AUDIO = 'START_MUTE_STREAME_AUDIO';
export const MERGE_CANVAS_WIDTH = 'MERGE_CANVAS_WIDTH';
export const CLEAR_AUDIODATA_STATE = 'CLEAR_AUDIODATA_STATE';

// blocks data types
export const SET_VISIBILITY = 'SET_VISIBILITY';

// Presets data types
export const SET_DEFAULT_PRESET = 'SET_DEFAULT_PRESET';
export const SET_JAZZ_PRESET = 'SET_JAZZ_PRESET';
export const SET_ROCK_PRESET = 'SET_ROCK_PRESET';
export const SET_POP_PRESET = 'SET_POP_PRESET';
export const SET_USER_PRESET = 'SET_USER_PRESET';
export const ADD_NEW_USER_PRESET_FROM_INPUT = 'ADD_NEW_USER_PRESET_FROM_INPUT';
export const ADD_NEW_USER_PRESET_FROM_DB = 'ADD_NEW_USER_PRESET_FROM_DB';
